version: "3"

services:
  balancer:
    container_name: "balancer"
    image: nginx:alpine
    volumes:
      - ./docker/balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - balancer
  web1:
    container_name: "web1"
    image: php:8.0-apache
    volumes:
      - ./html:/var/www/html
    ports:
      - 8081:80
    networks:
      - balancer
  web2:
    container_name: "web2"
    image: php:8.0-apache
    volumes:
      - ./html:/var/www/html
    ports:
      - 8082:80
    networks:
      - balancer
  web3:
    container_name: "web3"
    image: php:8.0-apache
    volumes:
      - ./html:/var/www/html
    ports:
      - 8083:80
    networks:
      - balancer

networks:
  balancer:
    driver: "bridge"
